
package my.restaurant.booking.jdbc;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;

/**
 *
 * @author Bánszki András <andras.banszki@gmail.com>
 */
public class MySqlConnector {
    
    private static final String URL = "jdbc:mysql://localhost:3306/restaurant?useSSL=false&serverTimezone=UTC";
    private static final String USERNAME = "root";
    private static final String PASSWORD = "admin";

    
    public Connection getConnection() throws SQLException {
        
        return DriverManager.getConnection(URL, USERNAME, PASSWORD);
    }
    
    /* 
    to be able to use prepareStatement in try with resource clauese, i made an own prepareStatement
    */
    public static PreparedStatement prepareStatement(Connection connection, String sql, PreparedStatementSetter setter) 
            throws SQLException {
        
            PreparedStatement ps = connection.prepareStatement( sql );
            setter.setValues(ps);
    return ps;
    }
    /*
    Same as above only change is the no of params to be able to get back int autoGeneratedKeys    
    */
    public static PreparedStatement prepareStatement(Connection connection, String sql, int autoGeneratedKeys, PreparedStatementSetter setter) 
            throws SQLException {
        
            PreparedStatement ps = connection.prepareStatement( sql, autoGeneratedKeys);
            setter.setValues(ps);
    return ps;
    }
    
}    

